### PR TITLE
Add responsability tracking file `CODEOWNERS`

### PR DESCRIPTION
**Pull request by jobwat**
We need an efficient way to find the owners of small projects internally at Airtasker.

Github offers a well thought after solution with the `CODEOWNERS` file.
https://github.blog/2017-07-06-introducing-code-owners/

### CODE REVIEW

**Comment by fwouts** [comment]
@jobwat I'm not familiar with .owners files. Do you have some context for this? This is an open-source project, by the way.

**Comment by jobwat** [comment]
Thanks for pointing up it's public

Github alerted about a vulnerability in this repo and I didn't know which project it was.
There is a discussion internally in #security and the idea of a `.owners` file to ease the tracking of responsibilities came up.
Mostly for dependencies projects like this.

**Comment by fwouts** [comment]
Have you considered GitHub's CODEOWNERS approach? See https://github.blog/2017-07-06-introducing-code-owners/

**Comment by jobwat** [comment]
Discovering it. Thanks

We'll have a discussion internally, I'll get back here

**Comment by jobwat** [comment]
PR updated

**Pull request merged**
